name: ecommerce
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  equatable:
  dartz:
  shared_preferences:
  http:
  internet_connection_checker:
  flutter_bloc:
  get_it:
  shimmer:
  cached_network_image:
  flutter_svg:
  dots_indicator:
  flutter_secure_storage:
  photo_view:
  dotted_border:
  flutter_local_notifications:
  share_plus:
  get_storage:
  screenshot:
  path_provider:
  url_launcher:
  flutter_phoenix:
  google_sign_in: ^6.1.4
  sign_in_with_apple: ^5.0.0
  # Firebase
  firebase_messaging: ^14.6.5
  firebase_auth: ^4.7.0
  firebase_core: ^2.15.0
  firebase_crashlytics: ^3.4.0
  cloud_firestore:
  uuid:
  firebase_storage:
  firebase_dynamic_links: ^5.4.3
  firebase_app_check:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/svg/
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
